# Generated by Django 5.2.3 on 2025-06-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='media',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.livre'),
            preserve_default=False,
        ),
    ]
