# Generated by Django 5.2.3 on 2025-06-23 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque_app', '0002_remove_emprunt_media_emprunt_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpruntCd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.cd')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.emprunteur')),
            ],
        ),
        migrations.CreateModel(
            name='EmpruntDvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.dvd')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.emprunteur')),
            ],
        ),
        migrations.CreateModel(
            name='EmpruntLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.emprunteur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque_app.livre')),
            ],
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
